#!/bin/bash
# this project has two versions, windows and linux.
# libraries, build files, etc are different, but source applies to both.
# sourcegit intends to automate pushing only source files to the master branch

if [ -z $1 ]; then
	echo oops, give a commit message!
	echo past commit messages:
	git log master -n 5 --pretty=oneline
	exit
fi

cd -P ~/gitclones/internship/qq
git stash
git checkout master

# the source directories
git checkout linux src/ include/ shaders/
git commit -m "$*"
git push origin master

git checkout linux
git stash pop
