#!/bin/bash

cd /home/craptop/gitclones/internship/MarchingCubes/MarchingCubes/build
make || exit

echo make successful! woo

printf "%*s\n" "${COLUMNS:-$(tput cols)}" "" | tr " " -

if [[ -n $1 ]]; then
	exit
fi

# return to the main project directory to access the shader and obj files
cd ..
# use OpenGL version 3.3 rather than the default
MESA_GL_VERSION_OVERRIDE=3.3 build/MarchingCubes
